# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript
variables:
  configuration: debug
  platform: x64
  -group: APP-VARS

trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

steps:

- task: NodeTool@0
  inputs:
    versionSpec: '16.15.1'
  displayName: 'Node install'

- script: |
    ls
  displayName: view dirs

- script: |
    yarn install
  displayName: 'Yarn install'

- script: | 
    npx playwright install --with-deps
  displayName: 'Install Playwright Browsers'

- script: | 
    npx playwright test --trace=on
  displayName: Run Playwright tests

- task: CopyFiles@2
  inputs:
    contents: '**/playwright-report/**/**.**'
    targetFolder: '$(build.artifactStagingDirectory)'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(build.artifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'

- task: DownloadBuildArtifacts@1
  inputs:
    buildType: 'current'
    downloadType: 'single'
    artifactName: 'drop'
    downloadPath: '$(System.ArtifactsDirectory)'